### ISSUE TITLE
Mcsearch online tool down?

### ISSUE THREAD

**Issue by mukhomorr** [HuanLab/McSearch#1]
Dear HuanLab,

I'd like to know, if the web version of McSearch tools is going to be online or supported in future? R script works just alright, but searching for related compounds through the site was very comfortable too? during my plant metabolomics research tasks.

**Comment by flynion** [comment]
Hi, Thanks for using the program. The website is current under maintenance. We will make it available to the public in a few weeks. Meanwhile, the R script should work in a similar way. Let us know if you find any problem of using it.
